name = "Create VC"
author = "Jammersmurph"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c61743914ff33b54b0ce6d35c697f25bac37c9974815674f6b8a86be933caa3d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
