name = "Create VC"
author = "Jammersmurph"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71e6c7c640175aa36dfba177ae61cf7f2683649fa603139cc076411de313159d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
